name: Build Android APK
on: [push, workflow_dispatch]

# নোড.জেএস এর ওয়ার্নিং ফিক্স করার জন্য এনভায়রনমেন্ট ভেরিয়েবল
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Fix Apt Error and Install Dependencies
        run: |
          # Exit code 100 ফিক্স করার জন্য ক্লিনআপ
          sudo rm -rf /var/lib/apt/lists/*
          sudo apt update || true
          sudo apt install -y git zip unzip autoconf automake libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev openjdk-17-jdk
          pip install --ignore-installed --user --upgrade Cython==0.29.33 buildozer setuptools

      - name: Build with Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # পাইথনের আধুনিক রেস্ট্রিকশন বাইপাস করা
          export PIP_BREAK_SYSTEM_PACKAGES=1
          yes | buildozer android debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: SecureSync-Release
          path: bin/*.apk
